/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Register2.java
 *
 * Created on Feb 21, 2019, 8:27:40 PM
 */

package traffic_management;

import java.awt.Color;

/**
 *
 * @author HP
 */
public class Register2 extends javax.swing.JFrame {

    /** Creates new form Register2 */
    public Register2() {
        initComponents();
       this.setLocationRelativeTo(null);
       this.setSize(1002,747);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        t1 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Albertus Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Complete your profile");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 200, 40);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\pics\\2.png")); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(940, 10, 40, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_management/Untitled.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(880, 10, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_management/Back.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 60);

        jLabel3.setFont(new java.awt.Font("Agate-Normal", 0, 18)); // NOI18N
        jLabel3.setText("Vehicle Registration Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 560, 260, 20);

        jLabel4.setFont(new java.awt.Font("Agate-Normal", 0, 18)); // NOI18N
        jLabel4.setText("Vehicle Category");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 470, 150, 20);

        jLabel5.setFont(new java.awt.Font("Agate-Normal", 0, 18)); // NOI18N
        jLabel5.setText("Vehicle Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 400, 150, 20);

        jLabel6.setFont(new java.awt.Font("Agate-Normal", 0, 18)); // NOI18N
        jLabel6.setText("Pickup Pincode ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 730, 150, 20);

        jLabel8.setFont(new java.awt.Font("Agate-Normal", 0, 18)); // NOI18N
        jLabel8.setText("Droping PIncode");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 640, 150, 23);

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setText("SUBMIT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 860, 110, 40);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Four Wheeler");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(740, 460, 107, 30);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Two Wheeler");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(510, 460, 105, 30);
        jPanel1.add(t1);
        t1.setBounds(510, 390, 350, 30);
        jPanel1.add(t5);
        t5.setBounds(440, 320, 140, 30);
        jPanel1.add(t2);
        t2.setBounds(510, 550, 350, 30);
        jPanel1.add(t6);
        t6.setBounds(720, 320, 140, 30);
        jPanel1.add(t3);
        t3.setBounds(510, 630, 350, 30);

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        jPanel1.add(t4);
        t4.setBounds(510, 720, 350, 30);

        jLabel13.setFont(new java.awt.Font("Agate-Normal", 0, 18)); // NOI18N
        jLabel13.setText("Working Timings (HH:MM:SS)");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(120, 330, 280, 20);

        jLabel12.setText("to");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(640, 330, 20, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(510, 250, 350, 30);

        jLabel7.setFont(new java.awt.Font("Agate-Normal", 0, 18)); // NOI18N
        jLabel7.setText("Company Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 250, 180, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setState(Register.ICONIFIED);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);       // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
jButton1.setBackground(new Color(240,240,240));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
jButton1.setBackground(new Color(102,255,102));
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Register frae = new Register();
frae.setVisible(true);
this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables

}
