/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Register.java
 *
 * Created on Feb 21, 2019, 4:54:23 PM
 */

package traffic_management;
import java.awt.Color;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Register extends javax.swing.JFrame {

    /** Creates new form Register */
    public Register() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Albertus Medium", 1, 18));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Register");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 80, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_management/Untitled.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(890, 10, 40, 40);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\pics\\2.png")); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(950, 10, 40, 40);

        jLabel2.setFont(new java.awt.Font("Albertus Medium", 1, 36));
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("REGISTER HERE !!!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 60, 350, 45);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_management/Back.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1000, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("For Hassle Free Ghaziabad");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 110, 290, 30);

        jLabel9.setFont(new java.awt.Font("Agate-Normal", 0, 18)); // NOI18N
        jLabel9.setText("Employee ID");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(100, 270, 130, 20);

        jLabel7.setFont(new java.awt.Font("Agate-Normal", 0, 18));
        jLabel7.setText("Employee Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 200, 144, 20);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(600, 190, 240, 30);

        jLabel8.setFont(new java.awt.Font("Agate-Normal", 0, 18)); // NOI18N
        jLabel8.setText("Date Of Birth (D.O.B)");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 340, 200, 20);
        jPanel1.add(t7);
        t7.setBounds(600, 550, 240, 30);

        jLabel10.setFont(new java.awt.Font("Agate-Normal", 0, 18));
        jLabel10.setText("Residence Contact No.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(100, 550, 220, 20);
        jPanel1.add(t3);
        t3.setBounds(600, 330, 240, 30);
        jPanel1.add(t2);
        t2.setBounds(600, 260, 240, 30);

        jLabel11.setFont(new java.awt.Font("Agate-Normal", 0, 18));
        jLabel11.setText("Address");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 410, 120, 20);

        jLabel12.setFont(new java.awt.Font("Agate-Normal", 0, 18));
        jLabel12.setText("Mobile No.");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(100, 480, 70, 20);
        jPanel1.add(t5);
        t5.setBounds(600, 400, 240, 30);

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        jPanel1.add(t6);
        t6.setBounds(600, 470, 240, 30);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Save & Continue");
        jButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 680, 210, 40);

        jLabel13.setFont(new java.awt.Font("Agate-Normal", 0, 18));
        jLabel13.setText("Email - Id");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(100, 630, 90, 20);
        jPanel1.add(t8);
        t8.setBounds(600, 620, 240, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_management/street-238458_1920.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 60, 1000, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setState(Register.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered

    jButton1.setBackground(new Color(51,255,51));    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String name = t1.getText();
String id = t2.getText();
String ta=t3.getText();
String too = t3.getText();
String ad = t5.getText();
String mob = t6.getText();
String resi =t7.getText();
String gam = t8.getText();
int l= id.length();
int lm = mob.length();
String uni_mob= mob.substring(l-5);
String uni_namid=id.substring(l-5);
String uniquei = uni_mob.concat(uni_namid);

try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/traffic","root","ashwin21");
Statement stmt = con.createStatement();
String query ="INSERT INTO register (emp,id,st_time,en_time,addr,mob,res_mob,gmai)VALUES('"+name+"','"+id+"','"+ta+"','"+too+"','"+ad+"','"+mob+"','"+resi+"','"+gam+"');";
stmt.executeUpdate(query);

JOptionPane.showMessageDialog(null,"Your Unique id is : "+uniquei+"\nKeep It Secure for Future Use .\nIt is Manadatory as a login Method");
        Register2 frame = new Register2();
frame.setVisible(true);
this.setVisible(false);
}
catch(Exception e )
{JOptionPane.showMessageDialog(null,e.getMessage());}
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
jButton1.setBackground(new java.awt.Color(0,153,153));
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t1ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables

}
